server:
  port: ${PORT:5001}
spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    tomcat:
      max-wait: 10000
      max-total: 10
      max-idle: 10
logging:
  level:
    net:
      dflmngr: ${DFLMNGR_LOG_LEVEL}